// <auto-generated />
using System;
using MedicalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606065902_AddDoctorLeaveAndSchedule")]
    partial class AddDoctorLeaveAndSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedicalSystem.Models.ActivityLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("MedicalSystem.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            location = "Block A, Level 1",
                            name = "Emergency Department (ER)",
                            status = 1
                        },
                        new
                        {
                            id = 2,
                            location = "Block B, Level 3",
                            name = "Cardiology",
                            status = 1
                        },
                        new
                        {
                            id = 3,
                            location = "Block B, Level 4",
                            name = "Neurology",
                            status = 1
                        },
                        new
                        {
                            id = 4,
                            location = "Block C, Level 2",
                            name = "Pediatrics",
                            status = 1
                        },
                        new
                        {
                            id = 5,
                            location = "Block D, Level 1",
                            name = "Oncology",
                            status = 1
                        },
                        new
                        {
                            id = 6,
                            location = "Block A, Level 2",
                            name = "Orthopedics",
                            status = 1
                        },
                        new
                        {
                            id = 7,
                            location = "Block A, Level 3",
                            name = "General Surgery",
                            status = 1
                        },
                        new
                        {
                            id = 8,
                            location = "Block A, Level 4",
                            name = "Intensive Care Unit (ICU)",
                            status = 1
                        },
                        new
                        {
                            id = 9,
                            location = "Block C, Basement 1",
                            name = "Radiology & Imaging",
                            status = 1
                        },
                        new
                        {
                            id = 10,
                            location = "Block A, Level 1",
                            name = "Pharmacy",
                            status = 1
                        },
                        new
                        {
                            id = 11,
                            location = "Block C, Level 3",
                            name = "Obstetrics and Gynecology",
                            status = 1
                        },
                        new
                        {
                            id = 12,
                            location = "Block B, Level 1",
                            name = "Dental Clinic",
                            status = 0
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateJoin")
                        .HasColumnType("date")
                        .HasColumnName("date_join");

                    b.Property<DateOnly?>("DateLeft")
                        .HasColumnType("date")
                        .HasColumnName("date_left");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_number");

                    b.Property<int?>("OfficeLocationId")
                        .HasColumnType("int")
                        .HasColumnName("office_location_id");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("office_phone");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("qualifications");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remark");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("work_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.DoctorLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_full_day");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int")
                        .HasColumnName("leave_type");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorLeaves");
                });

            modelBuilder.Entity("MedicalSystem.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("int")
                        .HasColumnName("slot_duration");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "DayOfWeek")
                        .IsUnique()
                        .HasFilter("is_active = 1");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("MedicalSystem.Models.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Male",
                            status = 1
                        },
                        new
                        {
                            id = 2,
                            name = "Female",
                            status = 1
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.OfficeLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("OfficeLocations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Consultation Room 101 (Block A, Level 1)",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Consultation Room 302 (Block B, Level 3)",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("allergies");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_type");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("chronic_diseases");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("EmergencyContactRelation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emergency_contact_relation");

                    b.Property<string>("IcNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ic_number");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("medical_notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.Position", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Chief Physician",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Associate Chief Physician",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Attending Physician",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "General Consultation (全科门诊)",
                            status = 1
                        },
                        new
                        {
                            id = 2,
                            name = "Cardiology (心脏专科)",
                            status = 1
                        },
                        new
                        {
                            id = 3,
                            name = "Dental Care (牙科门诊)",
                            status = 1
                        },
                        new
                        {
                            id = 4,
                            name = "Pediatrics (儿科门诊)",
                            status = 1
                        },
                        new
                        {
                            id = 5,
                            name = "Neurology (神经内科)",
                            status = 0
                        },
                        new
                        {
                            id = 6,
                            name = "Physiotherapy (康复理疗)",
                            status = 1
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.Specialty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "General Cardiology",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Clinical Neurology",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Pediatrics Care",
                            status = 1,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnOrder(30);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address_line_1")
                        .HasColumnOrder(12);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address_line_2")
                        .HasColumnOrder(13);

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city")
                        .HasColumnOrder(14);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnOrder(25);

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country")
                        .HasColumnOrder(17);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(18);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth")
                        .HasColumnOrder(11);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email")
                        .HasColumnOrder(3);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(23);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name")
                        .HasColumnOrder(2);

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id")
                        .HasColumnOrder(8);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(29);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(28);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(20);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(22);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password")
                        .HasColumnOrder(4);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(6);

                    b.Property<string>("PhoneNumberAlt")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number_alt")
                        .HasColumnOrder(7);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(26);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postal_code")
                        .HasColumnOrder(16);

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_image_url")
                        .HasColumnOrder(5);

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role")
                        .HasColumnOrder(9);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnOrder(24);

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state")
                        .HasColumnOrder(15);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasColumnOrder(10);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(27);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(19);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(21);

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a72b83c1-0c5a-4e67-8fa6-fb2a6cf124de",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pin@gmail.com",
                            EmailConfirmed = false,
                            FullName = "pin",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIN@GMAIL.COM",
                            NormalizedUserName = "PIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGQtk7e9UUo5gDcH2x8eCy4ZPGJgiEsNm02os9IGVlrsBv6x73FrBD8a9+N2YDPn+A==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 3,
                            SecurityStamp = "f4c9c7d1-e6df-46b0-9b62-fa583db13d5a",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "pin@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f93c1-cd2c-47ea-bcbf-11fc2cf00de8",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = false,
                            FullName = "superadmin",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAZMkCYvdl5kCQDKjBdPKq2Nk53w+yMOXe31+51DH0fNES+Mudcz8NUNs+6E7DDpuA==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "c95e1e0a-bf6b-4df2-823a-fcf723fbfa4b",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "superadmin@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d85fbc2a-1c3c-41ca-a2bf-23fc3df11de9",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FullName = "admin",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYr1FHHMBRqDO6CvXlPce5WS2N3UPoCKHcQbh2rLCHSuKCrGCJ5xruudBhlnEJn9g==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "e74c83fa-da13-4cb2-83b6-9df2cfd1e3ca",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f42fbc1a-5c2c-48ca-9dbf-34fc4df22de7",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor@gmail.com",
                            EmailConfirmed = false,
                            FullName = "doctor",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@GMAIL.COM",
                            NormalizedUserName = "DOCTOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOjhk8ytuqkUtAixRkugBso4C9ku8xjvWjK0e5nBJFW4A8rZk/v2yclWZYH7PtnUCg==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "a18d9bc1-df8a-4412-bd7c-2ef3cfb1c19b",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "doctor@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e95abc2d-0f9c-4df6-8fb2-14ac7df38de4",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient@gmail.com",
                            EmailConfirmed = false,
                            FullName = "patient",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@GMAIL.COM",
                            NormalizedUserName = "PATIENT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB7soW7G4QG3I/3BICSxwYEuPP+8DQ5gP9m2xD6c/h87k2SEbTi9Rj3z4JdoJUB4Mw==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 3,
                            SecurityStamp = "94fcbc12-d61a-4c91-9cb6-1ef2cfc3a5de",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "patient@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e36e8b41-db4a-4a2a-b73a-44d5cf3011ca",
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahpin7762@gmail.com",
                            EmailConfirmed = false,
                            FullName = "ahpin",
                            GenderId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHPIN7762@GMAIL.COM",
                            NormalizedUserName = "AHPIN7762@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBYB2JmumQLnDbJ0N1l0jX+z7nBAxRd0rCYZhuKUPRnnMOdgw/FmkgYoLD/nmOTvkg==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "782b3d2b-6c41-432d-948f-287d3a8fc4b1",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "ahpin7762@gmail.com"
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_refresh_tokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MedicalSystem.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalSystem.Models.DoctorLeave", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedicalSystem.Models.Doctor", "Doctor")
                        .WithMany("DoctorLeaves")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalSystem.Models.DoctorSchedule", b =>
                {
                    b.HasOne("MedicalSystem.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalSystem.Models.PatientProfile", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("MedicalSystem.Models.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalSystem.Models.User", b =>
                {
                    b.HasOne("MedicalSystem.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("MedicalSystem.Models.UserRefreshToken", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.Navigation("DoctorLeaves");
                });

            modelBuilder.Entity("MedicalSystem.Models.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
