// <auto-generated />
using System;
using MedicalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525090546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedicalSystem.Models.ActivityLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("MedicalSystem.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            location = "Block A, Level 1",
                            name = "Emergency Department (ER)",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            location = "Block B, Level 3",
                            name = "Cardiology",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            location = "Block B, Level 4",
                            name = "Neurology",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            location = "Block C, Level 2",
                            name = "Pediatrics",
                            status = true
                        },
                        new
                        {
                            id = 5,
                            location = "Block D, Level 1",
                            name = "Oncology",
                            status = true
                        },
                        new
                        {
                            id = 6,
                            location = "Block A, Level 2",
                            name = "Orthopedics",
                            status = true
                        },
                        new
                        {
                            id = 7,
                            location = "Block A, Level 3",
                            name = "General Surgery",
                            status = true
                        },
                        new
                        {
                            id = 8,
                            location = "Block A, Level 4",
                            name = "Intensive Care Unit (ICU)",
                            status = true
                        },
                        new
                        {
                            id = 9,
                            location = "Block C, Basement 1",
                            name = "Radiology & Imaging",
                            status = true
                        },
                        new
                        {
                            id = 10,
                            location = "Block A, Level 1",
                            name = "Pharmacy",
                            status = true
                        },
                        new
                        {
                            id = 11,
                            location = "Block C, Level 3",
                            name = "Obstetrics and Gynecology",
                            status = true
                        },
                        new
                        {
                            id = 12,
                            location = "Block B, Level 1",
                            name = "Dental Clinic",
                            status = false
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("biography")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateOnly>("date_join")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("date_left")
                        .HasColumnType("date");

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<string>("license_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("office_location_id")
                        .HasColumnType("int");

                    b.Property<string>("office_phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("postal_code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("qualifications")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("remark")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<byte[]>("resume_pdf")
                        .HasColumnType("longblob");

                    b.Property<int>("specialty_id")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("title_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("years_of_experience")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MedicalSystem.Models.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Male",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            name = "Female",
                            status = true
                        });
                });

            modelBuilder.Entity("MedicalSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnOrder(21);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnOrder(16);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email")
                        .HasColumnOrder(3);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(14);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(20);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(19);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password")
                        .HasColumnOrder(6);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(4);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(17);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnOrder(15);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(18);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasColumnOrder(9);

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name")
                        .HasColumnOrder(2);

                    b.Property<int?>("gender_id")
                        .HasColumnType("int")
                        .HasColumnName("gender_id")
                        .HasColumnOrder(5);

                    b.Property<int?>("genderid")
                        .HasColumnType("int");

                    b.Property<int?>("role")
                        .HasColumnType("int")
                        .HasColumnName("role")
                        .HasColumnOrder(8);

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("genderid");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a72b83c1-0c5a-4e67-8fa6-fb2a6cf124de",
                            Email = "pin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIN@GMAIL.COM",
                            NormalizedUserName = "PIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPC6RQV3Dczh6iVvJbdvLMa687d8pXOmeOI24vnHFVs0O1YetDWeYHaFBk2mwuz2QA==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4c9c7d1-e6df-46b0-9b62-fa583db13d5a",
                            TwoFactorEnabled = false,
                            UserName = "pin@gmail.com",
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            full_name = "pin",
                            gender_id = 1,
                            role = 3,
                            status = true,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b84f93c1-cd2c-47ea-bcbf-11fc2cf00de8",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOIjbEa20yRwpUvkVvb7VCcQhM012/1F77RAJfYmBCbwEbVUjxY3BFc0P+pd/Apffw==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c95e1e0a-bf6b-4df2-823a-fcf723fbfa4b",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@gmail.com",
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            full_name = "superadmin",
                            gender_id = 1,
                            role = 0,
                            status = true,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d85fbc2a-1c3c-41ca-a2bf-23fc3df11de9",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEwoRvDWldVdPhgSJI9KCnoQwoE15/P0kE6BVhVb7+lVAhhxzhGfRi9D7/DZU4ygHw==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e74c83fa-da13-4cb2-83b6-9df2cfd1e3ca",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com",
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            full_name = "admin",
                            gender_id = 1,
                            role = 1,
                            status = true,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f42fbc1a-5c2c-48ca-9dbf-34fc4df22de7",
                            Email = "doctor@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@GMAIL.COM",
                            NormalizedUserName = "DOCTOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPj3RHv+hVERV6rxzm6YRxT8cBnohe3qPTKR5MW4vxdpp5urqy3uiTn/kCZ6I7hmqw==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a18d9bc1-df8a-4412-bd7c-2ef3cfb1c19b",
                            TwoFactorEnabled = false,
                            UserName = "doctor@gmail.com",
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            full_name = "doctor",
                            gender_id = 1,
                            role = 2,
                            status = true,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e95abc2d-0f9c-4df6-8fb2-14ac7df38de4",
                            Email = "patient@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@GMAIL.COM",
                            NormalizedUserName = "PATIENT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKegiBQPGN/CpqAkTtPQjtgK8QNuBXc6xy6PyfCg7ayQxgq2JWMHfc38RKTSXpdbRw==",
                            PhoneNumber = "88888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94fcbc12-d61a-4c91-9cb6-1ef2cfc3a5de",
                            TwoFactorEnabled = false,
                            UserName = "patient@gmail.com",
                            created_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            full_name = "patient",
                            gender_id = 1,
                            role = 3,
                            status = true,
                            updated_at = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MedicalSystem.Models.User", b =>
                {
                    b.HasOne("MedicalSystem.Models.Gender", "gender")
                        .WithMany()
                        .HasForeignKey("genderid");

                    b.Navigation("gender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MedicalSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
